name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

     - name: Create .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
          init.author.name=Matt Oliver
          init.author.url=https://mattoliver.xyz
          init.author.email=mattoliver.mattoliver@gmail.com
          email=mattoliver.mattoliver@gmail.com
          registry=https://registry.npmjs.org
          always-auth=true
          //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Use cached node_modules 
        uses: actions/cache@v1
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('../yarn.lock') }}
          restore-keys: |
            nodeModules-
      
      - name: Create .yarnrc.yml
        run: |
          cat << EOF > "$HOME/.yarnrc.yml"
          EOF

      - name: Install Dependencies
        run: yarn

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          setupGitUser: true
          # Version PRs will fail unless the version is updated since automation systems rely on package=lock changes to use the install cache or not, see https://github.com/changesets/changesets/issues/421
          version: yarn changeset:version
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
